---
# Unittesting pre-change-checks role
- name: Pre-change-checks unit tests
  gather_facts: true
  hosts: aws_ec2  # Group name created automatically when aws ec2 hosts are being imported

  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

    - name: Perform pre-change tasks
      ansible.builtin.import_role:
        name: pre-change

  post_tasks:
    - name: Debug the outcome
      ansible.builtin.debug:
        msg:
          - "{{ inventory_hostname }} managed successfully "

    
    
    