---
# stitching the job-templates into a workflow
# 
- name: Create workflow job template for "{{ aws_infra_workflow_name }}"
  awx.awx.workflow_job_template:
    name: "{{ aws_infra_workflow_name }}"
    inventory: "{{ aws_ec2_inventory_name }}"
    organization: "{{ organization_name }}"
    state: present
    description: "{{ project_git_url }}"
  register: aws_ec2_workflow 

# Create workflow nodes
- name: Create workflow nodes 
  awx.awx.workflow_job_template_node:
    workflow: "{{ aws_ec2_workflow.id }}"
    identifier: "{{ item }}"
    organization: "{{ organization_name }}"
    unified_job_template: "job-{{ item }}"
    state: present
  loop:
    - "{{ aws_env_phase_1 }}"
    - "{{ aws_env_phase_2 }}"
    - "{{ aws_env_phase_3 }}"

- name: "Create {{ aws_infra_change_approval_node_name }} approval node"
  awx.awx.workflow_job_template_node:
    workflow: "{{ aws_ec2_workflow.id }}"
    identifier: "{{ aws_infra_change_approval_node_name }}"
    organization: "{{ organization_name }}"
    state: present
    approval_node:
        description: "Proceed with change?"
        name: "{{ aws_infra_change_approval_node_name }}"
        timeout: 3600 # The amount of time (in seconds) before the approval node expires and fails.

# Stitch job templates into a workflow

- name: "Link job-{{ aws_env_phase_1 }} workflow node to {{ aws_infra_change_approval_node_name }} node"
  awx.awx.workflow_job_template_node:
    workflow: "{{ aws_ec2_workflow.id }}"
    identifier: "{{ aws_env_phase_1 }}"
    organization: "{{ organization_name }}"
    success_nodes: 
      - "{{ aws_infra_change_approval_node_name }}"  # When successful moves to this

- name: "Link {{ aws_infra_change_approval_node_name }} node to {{ aws_env_phase_2 }} node"
  awx.awx.workflow_job_template_node:
    workflow: "{{ aws_ec2_workflow.id }}"
    identifier: "{{ aws_infra_change_approval_node_name }}"
    organization: "{{ organization_name }}"
    success_nodes: 
      - "{{ aws_env_phase_2 }}" # When successful moves to this

- name: "Link {{ aws_env_phase_2 }} node to {{ aws_env_phase_3 }} node"
  awx.awx.workflow_job_template_node:
    workflow: "{{ aws_ec2_workflow.id }}"
    identifier: "{{ aws_env_phase_2 }}"
    organization: "{{ organization_name }}"
    success_nodes: 
      - "{{ aws_env_phase_3 }}" # When successful moves to this
  
# Should I think of kick-starting this automatically?
# Not in the scope for now :)