---
# Build organization at the top
# REF: https://docs.ansible.com/ansible/latest/collections/awx/awx/organization_module.html

# Not defined exec env since that's actively defined in the jobs& work flow.

- name: Create organization = {{ organization_name }} 
  ansible.controller.organization:
    name: "{{ organization_name }}"
    description: "{{ project_git_url }}"
    state: present

