---
- name: Playbook to configure AAP 
  hosts: localhost
  gather_facts: false
  collections:
    - awx.awx

  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: group_vars

  roles:
    - role: organization
    - role: credential
    - role: project
    - role: inventory
    - role: template