---
# execute change
- name: Upgrade Debian Linux
  when: ansible_facts['os_family'] == 'Debian'
  ignore_errors: true
  block:
    # - name: Update package list (Debian/Ubuntu)
    #   ansible.builtin.apt:
    #     update_cache: yes
    
    - name: Install latest Python, Git, and Ansible (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - git
          - ansible
        state: latest
    

- name: Upgrade Redhat OS
  when: ansible_facts['os_family'] == 'RedHat'
  ignore_errors: true
  block:
    # - name: Update package list (RedHat/CentOS)
    #   ansible.builtin.yum:
    #     name: "*"
    #     state: latest
    
    - name: Install latest Python, Git, and Ansible (RedHat/CentOS)
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
          - git
          - ansible
        state: latest

- name: Ensure pip is upgraded to the latest version
  ansible.builtin.pip:
    name: pip
    state: latest
  ignore_errors: true